### ISSUE TITLE
The method driver /usr/lib/apt/methods/http could not be found

### ISSUE THREAD

**Issue by sirio81** [eLvErDe/hwraid#72] opened 2017-09-26 10:12 UTC
Sorry if I write here, this isn't a bug, but I hope it will save time to other users.
Problem:
  I got this error (italian)
  E: Impossibile trovare un driver per il metodo /usr/lib/apt/methods/http

I checked my sources.list multiple times and it was fine.
I noticed tough that nano hightlighting didn't color all the string:

`deb http://hwraid.le-vert.net/debian jessie main`

The words 'jessie' and 'main' were white instead of red and violet.

I changed the LANG variable to report the error in english
  export LANG='en_US'
Once I run 'nano /etc/apt/sources.list' I noticed there were **"strange" characters, between 'deb' and 'http'.**
Something like:
`deb **^ ^** http://hwraid.le-vert.net/debian jessie main`
So I understood the problem was about **copy / paste** from the Internet site!

So the solution is to delete those characters or **manually type all the string**.

**Comment by rfranlund** [comment] 2017-10-10 20:24
Thank you - I just had the exact same issue. Would have taken me quite some time to figure it out!

**Comment by dalu** [comment] 2017-11-06 17:50
This should be the number 1 search result on Google.

Alternatively the wiki maintainers could just use `<code></code>` to avoid this issue

**Comment by eLvErDe** [comment] 2017-11-06 18:28
I'm checking this, sorry guys

**Comment by eLvErDe** [comment] 2017-11-06 18:29
Can you confirm the issue is fixed now ?

**Comment by sirio81** [comment] 2017-11-06 20:53
Yes it is fixed.
Thank You!

**Closed** 2017-11-06 20:55 UTC
